# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkgJpsrPLf54vXV3wMqcJXu2RLl27OGj
"""

import streamlit as st
import pandas as pd
import os

# Archivo temporal para guardar predicciones
historial_path = "historial_predicciones.csv"
if not os.path.exists(historial_path):
    pd.DataFrame(columns=["FechaHora", "Cenizas", "PC"]).to_csv(historial_path, index=False)

# Leer historial completo
historial_df = pd.read_csv(historial_path)

# Si hay historial, proceder con la opción de eliminar
if not historial_df.empty:
    st.subheader("🗑️ Eliminar predicciones del historial")

    # Mostrar los primeros 20 registros en formato editable
    historial_df["Eliminar"] = False  # Columna para marcar las filas a eliminar
    edited_df = st.data_editor(historial_df, num_rows="dynamic", use_container_width=True)

    # Botón para eliminar filas marcadas
    if st.button("❌ Eliminar seleccionadas"):
        eliminadas = edited_df[edited_df["Eliminar"] == True]
        if not eliminadas.empty:
            # Filtrar las filas no marcadas para mantenerlas
            historial_df = edited_df[edited_df["Eliminar"] == False].drop(columns=["Eliminar"])
            # Guardar los cambios en el archivo
            historial_df.to_csv(historial_path, index=False)
            st.success(f"Se eliminaron {len(eliminadas)} predicciones.")
            st.rerun()  # Recargar la app para reflejar los cambios
        else:
            st.warning("No se seleccionaron filas para eliminar.")