# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkgJpsrPLf54vXV3wMqcJXu2RLl27OGj
"""

import streamlit as st
import numpy as np
import pandas as pd
import joblib
import datetime
import pytz
import plotly.graph_objects as go
import os
from io import BytesIO

# Cargar el modelo
modelo = joblib.load("PC_0.8722_12.04.pkl")

# Ruta para historial
historial_path = "historial_predicciones.csv"
if not os.path.exists(historial_path):
    pd.DataFrame(columns=["FechaHora", "Cenizas", "PC", "PC real", "Analista"]).to_csv(historial_path, index=False)

# Título
st.title("🔥 Predicción del Poder Calorífico del Carbón")
st.markdown("Ingrese los datos manualmente o pegue una fila completa separada por **coma, espacio o tabulación**.")

# Entrada rápida
st.subheader("📋 Entrada rápida (una línea completa)")
entrada_linea = st.text_input("Pegue aquí una fila completa con los 11 valores en orden:")

# Inicializa el estado de entrada manual
if "mostrar_manual" not in st.session_state:
    st.session_state.mostrar_manual = False

if st.button("📝 Mostrar entrada manual"):
    st.session_state.mostrar_manual = not st.session_state.mostrar_manual

# Lista de analistas
analistas = sorted(["Giomara C.", "Walter G.", "Julio O.", "Jhony V.", "Kenyi A."]) + ["Otros"]
analista = st.selectbox("👤 Seleccione el analista que realiza la predicción:", analistas)

# Entrada manual
if st.session_state.mostrar_manual:
    cenizas_bs = st.number_input("Cenizas (BS) (%)", min_value=0.0)
    sio2 = st.number_input("SiO2 ash (%)", min_value=0.0)
    al2o3 = st.number_input("Al2O3 ash (%)", min_value=0.0)
    fe2o3 = st.number_input("Fe2O3 ash (%)", min_value=0.0)
    cao = st.number_input("CaO ash (%)", min_value=0.0)
    mgo = st.number_input("MgO ash (%)", min_value=0.0)
    so3 = st.number_input("SO3 ash (%)", min_value=0.0)
    na2o = st.number_input("Na2O ash (%)", min_value=0.0)
    k2o = st.number_input("K2O ash (%)", min_value=0.0)
    s_carbon = st.number_input("S carbón (%)", min_value=0.0)
    cl_carbon = st.number_input("Cl carbón (%)", min_value=0.0)

# Validación

def validar_entrada(entrada):
    entrada = entrada.replace(",", ".")
    if entrada == "":
        return False
    try:
        valores = list(map(float, entrada.strip().split()))
        return len(valores) == 11
    except ValueError:
        return False

# Botón de predicción
if st.button("🔮 Predecir Poder Calorífico"):
    if entrada_linea:
        if not validar_entrada(entrada_linea):
            st.error("⚠️ Formato incorrecto. Ingrese exactamente 11 valores numéricos.")
            st.stop()

        sep = "," if "," in entrada_linea else "\t" if "\t" in entrada_linea else " "
        valores = list(map(float, entrada_linea.strip().split(sep)))
    else:
        valores = [cenizas_bs, sio2, al2o3, fe2o3, cao, mgo, so3, na2o, k2o, s_carbon, cl_carbon]

    valores_np = np.array(valores).reshape(1, -1)
    pc_predicho = modelo.predict(valores_np)[0]
    pc_entero = int(round(pc_predicho))

    st.success(f"🔥 Poder Calorífico Predicho: **{pc_entero} kcal/kg**")

    ahora_lima = datetime.datetime.now(pytz.timezone('America/Lima'))
    nuevo = pd.DataFrame([{
        "FechaHora": ahora_lima.strftime('%Y-%m-%d %H:%M:%S'),
        "Cenizas": valores[0],
        "PC": pc_entero,
        "PC real": None,
        "Analista": analista
    }])

    historial = pd.read_csv(historial_path)

    if "PC real" not in historial.columns:
        historial["PC real"] = None

    historial = pd.concat([historial, nuevo], ignore_index=True).tail(20)
    historial.to_csv(historial_path, index=False)

# Leer historial
historial = pd.read_csv(historial_path)
if "PC real" not in historial.columns:
    historial["PC real"] = None

# Gráfico
historial["FechaHora"] = pd.to_datetime(historial["FechaHora"], errors='coerce')
historial = historial.sort_values("FechaHora").tail(20)

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=historial["FechaHora"],
    y=historial["PC"],
    mode="lines",
    name="Tendencia PC",
    line=dict(color="orange", width=2)
))
fig.add_trace(go.Scatter(
    x=historial["FechaHora"],
    y=historial["PC"],
    mode="markers",
    name="Predicciones",
    marker=dict(
        size=historial["Cenizas"] * 2,
        color=historial["PC"],
        colorscale="YlOrRd",
        colorbar=dict(title="PC (kcal/kg)", len=0.75),
        showscale=True,
        line=dict(width=0.5, color='white')
    ),
    text=[
        f"Analista: {a}<br>PC: {pc:.0f} kcal/kg<br>Cenizas: {cen:.2f}%"
        for a, pc, cen in zip(historial["Analista"], historial["PC"], historial["Cenizas"])
    ],
    hoverinfo="text"
))
fig.update_layout(
    title="Poder Calorífico vs Fecha (ultimos 20 registros)",
    xaxis_title="Fecha y Hora",
    yaxis_title="Poder Calorífico (kcal/kg)",
    template="plotly_dark",
    hovermode="closest",
    height=500
)
st.plotly_chart(fig, use_container_width=True)

# Tabla editable
st.subheader("📃 Resumen de predicciones recientes (ultimos 20)")
historial_df = historial[["FechaHora", "Cenizas", "PC", "PC real", "Analista"]].copy()
historial_df["Eliminar"] = False

edited_df = st.data_editor(historial_df, num_rows="dynamic", use_container_width=True)

edited_df["Diferencia"] = np.where(
    pd.to_numeric(edited_df["PC real"], errors='coerce').notna(),
    pd.to_numeric(edited_df["PC real"], errors='coerce') - edited_df["PC"],
    np.nan
)

st.dataframe(edited_df[["FechaHora", "Cenizas", "PC", "PC real", "Diferencia", "Analista"]])

if st.button("📂 Guardar cambios y/o eliminar seleccionadas"):
    eliminadas = edited_df[edited_df["Eliminar"] == True]
    historial_actualizado = edited_df[edited_df["Eliminar"] == False].drop(columns=["Eliminar"])
    historial_actualizado.to_csv(historial_path, index=False)
    if not eliminadas.empty:
        st.success(f"Se eliminaron {len(eliminadas)} predicciones.")
    else:
        st.success("Cambios guardados correctamente.")
    st.rerun()

# Descargar Excel
st.subheader("📅 Descargar historial completo")
df_completo = pd.read_csv(historial_path)
buffer = BytesIO()
with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
    df_completo.to_excel(writer, index=False, sheet_name='Historial')
st.download_button(
    label="📄 Descargar en Excel",
    data=buffer.getvalue(),
    file_name="historial_predicciones.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)